---
# run dependencies
dep: True

# passwords
credentials_dir: '~/credentials/{{ ansible_hostname }}'
dim_database_passwd: "{{ lookup('password', credentials_dir + '/dim_database_passwd chars=ascii_letters,digits') }}"

# directories
dim_target_directory: /data/images
