---
# tasks file for apache

- name: install apache
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - httpd
    - mod_wsgi

- name: make sure apache is started on boot
  become: yes
  service:  name=httpd
            state=started
            enabled=yes