---
# tasks file for apache

- name: install apache
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - httpd
    - mod_wsgi

- name: Install configuration to access /data directory using the /sites url
  become: yes
  copy:
     src=files/images.conf
     dest=/etc/httpd/conf.d/images.conf


- name: make sure apache is started on boot
  become: yes
  service:  name=httpd
            state=started
            enabled=yes
