---
# tasks file for django-app

- name: add django user
  become: yes
  user: name="{{ app_user }}"
        state=present
        shell=/bin/bash

- name: add django project folder
  become: yes
  file: path={{ item }}
        state=directory
        mode=0755
        recurse=yes
        owner="{{ app_user }}"
        group=apache
  with_items:
    - "{{ project_path }}"
    - "{{ django_path }}"

- name: create django virtualenv
  become: yes
  become_user: "{{ app_user }}"
  shell: virtualenv venv
  args:
    chdir: "{{ project_path }}"
    executable: /bin/bash
    creates: "{{ django_virtualenv }}/bin/python"

- name: upgrade pip
  become: yes
  become_user: "{{ app_user }}"
  pip:  name=pip
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}

- name: clone git repository of coastal-image-browser
  become: yes
  become_user: "{{ app_user }}"
  git:
    repo: https://github.com/openearth/coastal-image-browser.git
    dest: "{{ django_path }}"
    update: yes

- name: install django
  become: yes
  become_user: django
  pip:  requirements="{{ django_path }}/requirements.txt"
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}

- name: Add apache to django group
  become: yes
  user: name=httpd
        groups="{{ app_user }}"
        append=yes

- name: Install wsgi configuration into apache
  become: yes
  template: src=../templates/02_django.j2 dest=/etc/httpd/conf.d/02_django.conf owner=apache group=apache mode=0644
  notify: restart apache